batch_type: numel
batch_bins: 200000000
accum_grad: 8
max_epoch: 200
patience: none
init: none
best_model_criterion:
-   - valid
    - acc
    - max
keep_nbest_models: 10
# use_amp: true       # automatic mixed precision (amp)
num_workers: 4
num_iters_per_epoch: 500

encoder: conformer
encoder_conf:
    output_size: 1024
    attention_heads: 8
    linear_units: 2048
    num_blocks: 12
    dropout_rate: 0.1
    positional_dropout_rate: 0.1
    attention_dropout_rate: 0.1
    input_layer: conv2d2
    normalize_before: true
    macaron_style: true
    rel_pos_type: latest
    pos_enc_layer_type: rel_pos
    selfattention_layer_type: rel_selfattn
    activation_type: swish
    use_cnn_module: true
    cnn_module_kernel: 31

extra_asr_decoder: transformer
extra_asr_decoder_conf:
    num_blocks: 6
    attention_heads: 8
    linear_units: 2048
    dropout_rate: 0.1
    positional_dropout_rate: 0.1
    self_attention_dropout_rate: 0.1
    src_attention_dropout_rate: 0.1

postencoder: length_adaptor
postencoder_conf:
    length_adaptor_n_layers: 1


decoder: hugging_face_transformers
decoder_conf:
    model_name_or_path: /scratch/bbjs/yan2/espnet-ml/egs2/must_c_v2/st1/mbart-large-50-many-to-many-mmt


model_conf:
    asr_weight: 0.3
    mt_weight: 0.0
    mtlalpha: 0.3
    st_mtlalpha: 0.3
    lsm_weight: 0.2
    length_normalized_loss: false
    extract_feats_in_collect_stats: false
    tgt_ignore_id: 1
    tgt_sym_blank: "<pad>"
    tgt_sym_sos: "<s>"
    tgt_sym_eos: "</s>"
    lang_token_id: 250003   #de_DE

optim: adam
optim_conf:
    lr: 0.0005
    weight_decay: 0.000001
scheduler: warmuplr
scheduler_conf:
    warmup_steps: 2500

specaug: specaug
specaug_conf:
    apply_time_warp: true
    time_warp_window: 5
    time_warp_mode: bicubic
    apply_freq_mask: true
    freq_mask_width_range:
    - 0
    - 27
    num_freq_mask: 2
    apply_time_mask: true
    time_mask_width_ratio_range:
    - 0.
    - 0.05
    num_time_mask: 5

freeze_param: [
"frontend.upstream",
"decoder.decoder.layers.0.fc1",
"decoder.decoder.layers.0.fc2",
"decoder.decoder.layers.1.fc1",
"decoder.decoder.layers.1.fc2",
"decoder.decoder.layers.2.fc1",
"decoder.decoder.layers.2.fc2",
"decoder.decoder.layers.3.fc1",
"decoder.decoder.layers.3.fc2",
"decoder.decoder.layers.4.fc1",
"decoder.decoder.layers.4.fc2",
"decoder.decoder.layers.5.fc1",
"decoder.decoder.layers.5.fc2",
"decoder.decoder.layers.6.fc1",
"decoder.decoder.layers.6.fc2",
"decoder.decoder.layers.7.fc1",
"decoder.decoder.layers.7.fc2",
"decoder.decoder.layers.8.fc1",
"decoder.decoder.layers.8.fc2",
"decoder.decoder.layers.9.fc1",
"decoder.decoder.layers.9.fc2",
"decoder.decoder.layers.10.fc1",
"decoder.decoder.layers.10.fc2",
"decoder.decoder.layers.11.fc1",
"decoder.decoder.layers.11.fc2",
"decoder.decoder.layers.0.self_attn",
"decoder.decoder.layers.1.self_attn",
"decoder.decoder.layers.2.self_attn",
"decoder.decoder.layers.3.self_attn",
"decoder.decoder.layers.4.self_attn",
"decoder.decoder.layers.5.self_attn",
"decoder.decoder.layers.6.self_attn",
"decoder.decoder.layers.7.self_attn",
"decoder.decoder.layers.8.self_attn",
"decoder.decoder.layers.9.self_attn",
"decoder.decoder.layers.10.self_attn",
"decoder.decoder.layers.11.self_attn",
]

frontend: s3prl
frontend_conf:
    frontend_conf:
        upstream: wavlm_large  # Note: If the upstream is changed, please change the input_size in the preencoder.
    download_dir: ./hub
    multilayer_feature: True

preencoder: linear
preencoder_conf:
    input_size: 1024  # Note: If the upstream is changed, please change this value accordingly.
    output_size: 80

ignore_init_mismatch: true
init_param:
    - "/scratch/bbjs/yan2/espnet-ml/egs2/must_c_v2/asr1/exp/asr_train_asr_conformer_wavlm_large_pre_lr0.001_raw_bpe4000_sp/valid.acc.ave_5best.pth:encoder:encoder"
    - "/scratch/bbjs/yan2/espnet-ml/egs2/must_c_v2/asr1/exp/asr_train_asr_conformer_wavlm_large_pre_lr0.001_raw_bpe4000_sp/valid.acc.ave_5best.pth:decoder:extra_asr_decoder"
    - "/scratch/bbjs/yan2/espnet-ml/egs2/must_c_v2/asr1/exp/asr_train_asr_conformer_wavlm_large_pre_lr0.001_raw_bpe4000_sp/valid.acc.ave_5best.pth:ctc:ctc"
    - "/scratch/bbjs/yan2/espnet-ml/egs2/must_c_v2/asr1/exp/asr_train_asr_conformer_wavlm_large_pre_lr0.001_raw_bpe4000_sp/valid.acc.ave_5best.pth:frontend.featurizer:frontend.featurizer"
    - "/scratch/bbjs/yan2/espnet-ml/egs2/must_c_v2/asr1/exp/asr_train_asr_conformer_wavlm_large_pre_lr0.001_raw_bpe4000_sp/valid.acc.ave_5best.pth:preencoder:preencoder"