frontend_conf:
    n_fft: 512
    win_length: 400
    hop_length: 112

specaug: specaug
specaug_conf:
    apply_time_warp: true
    time_warp_window: 5
    time_warp_mode: bicubic
    apply_freq_mask: true
    freq_mask_width_range:
    - 0
    - 27
    num_freq_mask: 2
    apply_time_mask: true
    time_mask_width_ratio_range:
    - 0.
    - 0.05
    num_time_mask: 2

encoder: conformer
encoder_conf:
    output_size: 256
    attention_heads: 4
    linear_units: 2048
    num_blocks: 12
    dropout_rate: 0.1
    positional_dropout_rate: 0.1
    attention_dropout_rate: 0.1
    input_layer: conv2d
    normalize_before: true
    macaron_style: true
    rel_pos_type: latest
    pos_enc_layer_type: rel_pos
    selfattention_layer_type: rel_selfattn
    activation_type: swish
    use_cnn_module: true
    cnn_module_kernel: 31

decoder: transformer_md
decoder_conf:
    attention_heads: 4
    linear_units: 2048
    num_blocks: 6
    dropout_rate: 0.1
    positional_dropout_rate: 0.1
    self_attention_dropout_rate: 0.1
    src_attention_dropout_rate: 0.1

asr_decoder: transformer
asr_decoder_conf:
    attention_heads: 4
    linear_units: 2048
    num_blocks: 6
    dropout_rate: 0.1
    positional_dropout_rate: 0.1
    self_attention_dropout_rate: 0.1
    src_attention_dropout_rate: 0.1

encoder_mt: transformer
encoder_mt_conf:
    input_layer: null
    num_blocks: 2
    linear_units: 2048
    dropout_rate: 0.1

model_conf:
    mtlalpha: 0.3
    mt_weight: 0.0
    asr_weight: 0.3
    lsm_weight: 0.1
    length_normalized_loss: false

use_amp: true       # automatic mixed precision (amp)
num_workers: 4
batch_type: numel
batch_bins: 6250000
accum_grad: 8
max_epoch: 60
patience: none
init: none
best_model_criterion:
-   - valid
    - acc
    - max
keep_nbest_models: 10

optim: adam
optim_conf:
    lr: 0.002
    weight_decay: 0.000005
scheduler: warmuplr
scheduler_conf:
    warmup_steps: 15000

ignore_init_mismatch: true
init_param:
    - "/projects/tir6/general/sdalmia/sid-espnet/egs2/iwslt22_dialect/st1/exp/asr_train_asr_conformer_hop112_raw_bpe1000_sp/valid.acc.ave_10best.pth:encoder:encoder"
