batch_size: 1
beam_size: 5
penalty: 0.0
maxlenratio: 4.0
minlenratio: 0.0
lm_weight: 0.0
ctc_weight: 0.0
sim_chunk_length: 32000
disable_repetition_detection: false
decoder_text_length_limit: 0
encoded_feat_length_limit: 0
incremental_decode: true

asr_beam_size: 5
asr_penalty: 0.0
asr_maxlenratio: 0.0
asr_minlenratio: 0.0
asr_lm_weight: 0.0
hugging_face_decoder: True
asr_ctc_weight: 0.3
asr_disable_repetition_detection: false
asr_decoder_text_length_limit: 0
asr_encoded_feat_length_limit: 0
asr_incremental_decode: true